# Site settings
title: Plus Equal
email: plusequal@fsto.co
description: > # this means to ignore newlines until "baseurl:"
  Plus Equal Workshops are professional development for developers working with advanced technologies. Register today for our next workshop!
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://plusequaltech.com" # the base hostname & protocol for your site
twitter_username: plusequaltech
github_username:  plusequal

# Build settings
markdown: kramdown
